/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vrgatherei16.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * not in op enum -> dispatcher illegal
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vle16.v v16,(%[B])\n"
    "vrgatherei16.vv v24,v8,v16\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[vl]"r"(16UL) : "t0","t1","memory");
    report_e32("vrgatherei16.vv e32 m1", R, 16);
    VEND();
    return 0;
}
