/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for bgeu. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    asm volatile("bgeu %1,%2,1f\n li %0,0\n j 2f\n 1: li %0,1\n 2:":"=r"(o):"r"(5L),"r"(5L)); R[0]=(uint64_t)o;
    asm volatile("bgeu %1,%2,1f\n li %0,0\n j 2f\n 1: li %0,1\n 2:":"=r"(o):"r"(5L),"r"(6L)); R[1]=(uint64_t)o;
    asm volatile("bgeu %1,%2,1f\n li %0,0\n j 2f\n 1: li %0,1\n 2:":"=r"(o):"r"(-1L),"r"(1L)); R[2]=(uint64_t)o;
    asm volatile("bgeu %1,%2,1f\n li %0,0\n j 2f\n 1: li %0,1\n 2:":"=r"(o):"r"(0L),"r"(0L)); R[3]=(uint64_t)o;
    asm volatile("bgeu %1,%2,1f\n li %0,0\n j 2f\n 1: li %0,1\n 2:":"=r"(o):"r"(-5L),"r"(-6L)); R[4]=(uint64_t)o;
    report_e64("bgeu", R, 5);
    VEND();
    return 0;
}
