/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for addw. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(0x0123456789ABCDEFL),"r"(0x55AA55AA55AA55AAL)); R[0]=(uint64_t)o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(0xFFFFFFFFFFFFFFFFL),"r"(1L)); R[1]=(uint64_t)o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(0x8000000000000000L),"r"(0xFFFFFFFFFFFFFFFFL)); R[2]=(uint64_t)o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(0x000000007FFFFFFFL),"r"(0x0000000080000000L)); R[3]=(uint64_t)o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(42L),"r"(-7L)); R[4]=(uint64_t)o;
    asm volatile("addw %0,%1,%2":"=r"(o):"r"(-1L),"r"(0x40L)); R[5]=(uint64_t)o;
    report_e64("addw", R, 6);
    VEND();
    return 0;
}
