/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vs1r.v.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * whole-register store, 1 reg(s)
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vl1re32.v v8,(%[A])\n"
    "vs1r.v v8,(%[R])\n"
    "vsetivli t0,8,e32,m1,ta,ma\n"
    "vle32.v v16,(%[R])\n"
    "vse32.v v16,(%[R])\n"
    :: [A]"r"(A),[R]"r"(R),[vl]"r"(8UL) : "t0","t1","memory");
    report_e32("vs1r.v (first 8 e32)", R, 8);
    VEND();
    return 0;
}
