/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vsext.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * sign-extend vf2/vf4/vf8
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e16,m1,ta,ma\n"
    "vle8.v v8,(%[A])\n"
    "vsext.vf2 v24,v8\n vse16.v v24,(%[R])\n"
    :: [A]"r"(A),[R]"r"(R),[vl]"r"(37UL) : "t0","memory");
    report_e16("vsext.vf2 e8->e16 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle8.v v8,(%[A])\n"
    "vsext.vf4 v24,v8\n vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[R]"r"(R),[vl]"r"(37UL) : "t0","memory");
    report_e32("vsext.vf4 e8->e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vle8.v v8,(%[A])\n"
    "vsext.vf8 v24,v8\n vse64.v v24,(%[R])\n"
    :: [A]"r"(A),[R]"r"(R),[vl]"r"(37UL) : "t0","memory");
    report_e64("vsext.vf8 e8->e64 m1 avl=37", R, 37);
    VEND();
    return 0;
}
