/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vmacc.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e8,m1,ta,ma\n"
    "vle8.v v24,(%[D])\n"
    "vle8.v v8,(%[A])\n"
    "vle8.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse8.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e8("vmacc.vv e8 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e16,m1,ta,ma\n"
    "vle16.v v24,(%[D])\n"
    "vle16.v v8,(%[A])\n"
    "vle16.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse16.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e16("vmacc.vv e16 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vv e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vle64.v v24,(%[D])\n"
    "vle64.v v8,(%[A])\n"
    "vle64.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse64.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e64("vmacc.vv e64 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m2,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vv e32 m2 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m8,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vv e32 m8 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,mf2,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vv e32 mf2 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "li t1,19\n"
    "vle32.v v8,(%[A])\n"
    "vmacc.vx v24,t1,v8\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vx e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,mu\n"
    "vlm.v v0,(%[M])\n"
    "vle32.v v24,(%[D])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16,v0.t\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmacc.vv e32 m1 masked(mu) avl=37", R, 37);

    asm volatile(
    "vsetivli t0,8,e32,m1,ta,ma\n"
    "vle32.v v24,(%[D])\n"
    "vsetvli t0,zero,e32,m1,tu,ma\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmacc.vv v24,v8,v16\n"
    "vsetivli t0,8,e32,m1,ta,ma\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[D]"r"(D0) : "t0","t1","memory");
    report_e32("vmacc.vv e32 m1 vl=0(dest preserved)", R, 8);
    VEND();
    return 0;
}
