/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vsse64.v.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * strided store
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vle64.v v8,(%[A])\n"
    "vsse64.v v8,(%[R]),%[st]\n"
    "vlse64.v v16,(%[R]),%[st]\n"
    "vse64.v v16,(%[D])\n"
    :: [A]"r"(A),[R]"r"(R),[D]"r"(D0),[vl]"r"(24UL),[st]"r"(16UL) : "t0","t1","memory");
    report_e64("vsse64.v m1 avl=24 stride=16B", D0, 24);
    VEND();
    return 0;
}
