/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for fcvt.d.l. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o; double dd; float ff; (void)dd;(void)ff;
    asm volatile("fsrmi 0\n fcvt.d.l ft0,%1\n fsd ft0,0(%[r])"::[r]"r"(&R[0]),"r"(0x0123456789ABCDEFL):"ft0","memory"); o=0;
    asm volatile("fsrmi 0\n fcvt.d.l ft0,%1\n fsd ft0,0(%[r])"::[r]"r"(&R[1]),"r"(0xFFFFFFFFFFFFFFFFL):"ft0","memory"); o=0;
    asm volatile("fsrmi 0\n fcvt.d.l ft0,%1\n fsd ft0,0(%[r])"::[r]"r"(&R[2]),"r"(0x8000000000000000L):"ft0","memory"); o=0;
    asm volatile("fsrmi 0\n fcvt.d.l ft0,%1\n fsd ft0,0(%[r])"::[r]"r"(&R[3]),"r"(0x000000007FFFFFFFL):"ft0","memory"); o=0;
    asm volatile("fsrmi 0\n fcvt.d.l ft0,%1\n fsd ft0,0(%[r])"::[r]"r"(&R[4]),"r"(42L):"ft0","memory"); o=0;
    report_e64("fcvt.d.l", R, 5);
    VEND();
    return 0;
}
