/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vsoxei64.v.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * indexed-ordered (scatter) store
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;
static uint8_t IDX[512] L2BUF;   /* index vector for indexed load/store (filled per-kernel) */

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    for (int _i = 0; _i < 24; _i++) ((uint64_t *)IDX)[_i] = (uint64_t)((24 - 1 - _i) * 8);
    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vle64.v v16,(%[I])\n"
    "vle64.v v8,(%[A])\n"
    "vsoxei64.v v8,(%[R]),v16\n"
    "vloxei64.v v24,(%[R]),v16\n"
    "vse64.v v24,(%[D])\n"
    :: [A]"r"(A),[I]"r"(IDX),[R]"r"(R),[D]"r"(D0),[vl]"r"(24UL) : "t0","t1","memory");
    report_e64("vsoxei64.v m1 avl=24", D0, 24);
    VEND();
    return 0;
}
