/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for amoswap.w. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    ((volatile uint64_t*)MEM)[0]=0x0F0F0F0F0F0F0F0FULL;
    asm volatile("amoswap.w %0,%2,(%1)":"=r"(o):"r"(MEM),"r"(0x11111111L):"memory"); R[0]=(uint64_t)o;
    R[1]=((volatile uint64_t*)MEM)[0];
    asm volatile("amoswap.w %0,%2,(%1)":"=r"(o):"r"(MEM),"r"(0xFFFFFFFFL):"memory"); R[2]=(uint64_t)o;
    R[3]=((volatile uint64_t*)MEM)[0];
    asm volatile("amoswap.w %0,%2,(%1)":"=r"(o):"r"(MEM),"r"(0x80000000L):"memory"); R[4]=(uint64_t)o;
    R[5]=((volatile uint64_t*)MEM)[0];
    report_e64("amoswap.w", R, 6);
    VEND();
    return 0;
}
