/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vmadc.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * produce carry-out mask
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e8,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle8.v v8,(%[A])\n"
    "vle8.v v16,(%[B])\n"
    "vmadc.vvm v24,v8,v16,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vvm e8 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e16,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle16.v v8,(%[A])\n"
    "vle16.v v16,(%[B])\n"
    "vmadc.vvm v24,v8,v16,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vvm e16 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmadc.vvm v24,v8,v16,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vvm e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle64.v v8,(%[A])\n"
    "vle64.v v16,(%[B])\n"
    "vmadc.vvm v24,v8,v16,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vvm e64 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "li t1,21\n"
    "vle32.v v8,(%[A])\n"
    "vmadc.vxm v24,v8,t1,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vxm e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle32.v v8,(%[A])\n"
    "vmadc.vim v24,v8,5,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vim e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmadc.vv v24,v8,v16\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vv e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "li t1,21\n"
    "vle32.v v8,(%[A])\n"
    "vmadc.vx v24,v8,t1\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vx e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vmadc.vi v24,v8,5\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vi e32 m1 avl=32", R, 4);

    asm volatile(
    "vsetvli t0,%[vl],e32,m2,ta,ma\n"
    "vlm.v v0,(%[M])\n"
    "vle32.v v8,(%[A])\n"
    "vle32.v v16,(%[B])\n"
    "vmadc.vvm v24,v8,v16,v0\n"
    "vsm.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(32UL) : "t0","t1","memory");
    report_bytes("vmadc.vvm e32 m2 avl=32", R, 4);
    VEND();
    return 0;
}
