/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for andi. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    asm volatile("andi %0,%1,0":"=r"(o):"r"(0x0123456789ABCDEFL)); R[0]=(uint64_t)o;
    asm volatile("andi %0,%1,1":"=r"(o):"r"(0xFFFFFFFFFFFFFFFFL)); R[1]=(uint64_t)o;
    asm volatile("andi %0,%1,-1":"=r"(o):"r"(0x8000000000000000L)); R[2]=(uint64_t)o;
    asm volatile("andi %0,%1,2047":"=r"(o):"r"(0x000000007FFFFFFFL)); R[3]=(uint64_t)o;
    asm volatile("andi %0,%1,-2048":"=r"(o):"r"(42L)); R[4]=(uint64_t)o;
    asm volatile("andi %0,%1,100":"=r"(o):"r"(-1L)); R[5]=(uint64_t)o;
    report_e64("andi", R, 6);
    VEND();
    return 0;
}
