/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for auipc. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o, o2; (void)o2;
    asm volatile("auipc %0,0\n auipc %1,0\n sub %0,%0,%1":"=r"(o),"=r"(o2)); R[0]=(uint64_t)o;
    asm volatile("auipc %0,1\n auipc %1,0\n sub %0,%0,%1":"=r"(o),"=r"(o2)); R[1]=(uint64_t)o;
    asm volatile("auipc %0,0xFFFFF\n auipc %1,0\n sub %0,%0,%1":"=r"(o),"=r"(o2)); R[2]=(uint64_t)o;
    asm volatile("auipc %0,0x80000\n auipc %1,0\n sub %0,%0,%1":"=r"(o),"=r"(o2)); R[3]=(uint64_t)o;
    asm volatile("auipc %0,0x12345\n auipc %1,0\n sub %0,%0,%1":"=r"(o),"=r"(o2)); R[4]=(uint64_t)o;
    report_e64("auipc", R, 5);
    VEND();
    return 0;
}
