/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for lui. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o, o2; (void)o2;
    asm volatile("lui %0,0":"=r"(o)); R[0]=(uint64_t)o;
    asm volatile("lui %0,1":"=r"(o)); R[1]=(uint64_t)o;
    asm volatile("lui %0,0xFFFFF":"=r"(o)); R[2]=(uint64_t)o;
    asm volatile("lui %0,0x80000":"=r"(o)); R[3]=(uint64_t)o;
    asm volatile("lui %0,0x12345":"=r"(o)); R[4]=(uint64_t)o;
    report_e64("lui", R, 5);
    VEND();
    return 0;
}
