/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for csrrs. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * read/write CSR (e.g. vl, vtype, fcsr, cycle)
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    asm volatile("csrw fcsr,zero");
    asm volatile("csrw fcsr,zero\n csrrs %0,fcsr,%1":"=r"(o):"r"(7L)); R[0]=(uint64_t)o;
    {long f; asm volatile("csrr %0,fcsr":"=r"(f)); R[1]=(uint64_t)f;}
    asm volatile("csrw fcsr,zero\n csrrs %0,fcsr,%1":"=r"(o):"r"(0L)); R[2]=(uint64_t)o;
    {long f; asm volatile("csrr %0,fcsr":"=r"(f)); R[3]=(uint64_t)f;}
    asm volatile("csrw fcsr,zero\n csrrs %0,fcsr,%1":"=r"(o):"r"(0xFFL)); R[4]=(uint64_t)o;
    {long f; asm volatile("csrr %0,fcsr":"=r"(f)); R[5]=(uint64_t)f;}
    report_e64("csrrs", R, 6);
    VEND();
    return 0;
}
