/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vmv.s.x.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * x reg -> element0
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e8,m1,ta,ma\n"
    "li t1,0x5a5a\n"
    "vmv.s.x v24,t1\n"
    "vse8.v v24,(%[R])\n"
    :: [R]"r"(R),[vl]"r"(37UL) : "t0","t1","memory");
    report_e8("vmv.s.x e8 m1", R, 1);

    asm volatile(
    "vsetvli t0,%[vl],e16,m1,ta,ma\n"
    "li t1,0x5a5a\n"
    "vmv.s.x v24,t1\n"
    "vse16.v v24,(%[R])\n"
    :: [R]"r"(R),[vl]"r"(37UL) : "t0","t1","memory");
    report_e16("vmv.s.x e16 m1", R, 1);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "li t1,0x5a5a\n"
    "vmv.s.x v24,t1\n"
    "vse32.v v24,(%[R])\n"
    :: [R]"r"(R),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.s.x e32 m1", R, 1);

    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "li t1,0x5a5a\n"
    "vmv.s.x v24,t1\n"
    "vse64.v v24,(%[R])\n"
    :: [R]"r"(R),[vl]"r"(37UL) : "t0","t1","memory");
    report_e64("vmv.s.x e64 m1", R, 1);
    VEND();
    return 0;
}
