/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vsetvl.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * register vtype form
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t5,%[avl],e8,m1,ta,ma\n"
    "csrr t4,0xC21\n"
    "vsetvl t1,%[avl],t4\n"
    "sd t1,0(%[R])\n"
    "csrr t2,0xC21\n"
    "sd t2,8(%[R])\n"
    :: [R]"r"(R),[avl]"r"(20UL) : "t1","t2","t3","t4","t5","memory");
    report_e64("vsetvl e8 m1 avl=20 -> [vl,vtype]", R, 2);

    asm volatile(
    "vsetvli t5,%[avl],e32,m1,ta,ma\n"
    "csrr t4,0xC21\n"
    "vsetvl t1,%[avl],t4\n"
    "sd t1,0(%[R])\n"
    "csrr t2,0xC21\n"
    "sd t2,8(%[R])\n"
    :: [R]"r"(R),[avl]"r"(17UL) : "t1","t2","t3","t4","t5","memory");
    report_e64("vsetvl e32 m1 avl=17 -> [vl,vtype]", R, 2);

    asm volatile(
    "vsetvli t5,%[avl],e64,m2,ta,ma\n"
    "csrr t4,0xC21\n"
    "vsetvl t1,%[avl],t4\n"
    "sd t1,0(%[R])\n"
    "csrr t2,0xC21\n"
    "sd t2,8(%[R])\n"
    :: [R]"r"(R),[avl]"r"(30UL) : "t1","t2","t3","t4","t5","memory");
    report_e64("vsetvl e64 m2 avl=30 -> [vl,vtype]", R, 2);

    asm volatile(
    "vsetvli t5,%[avl],e16,mf2,ta,ma\n"
    "csrr t4,0xC21\n"
    "vsetvl t1,%[avl],t4\n"
    "sd t1,0(%[R])\n"
    "csrr t2,0xC21\n"
    "sd t2,8(%[R])\n"
    :: [R]"r"(R),[avl]"r"(10UL) : "t1","t2","t3","t4","t5","memory");
    report_e64("vsetvl e16 mf2 avl=10 -> [vl,vtype]", R, 2);
    VEND();
    return 0;
}
