#!/usr/bin/env python3
"""
merge.py - build the master tracking log from per-kernel result.json files.

Reads every flow/verif/build/<group>/<name>/result.json (each written
independently by verify_one.py, so this is a consistent-set rebuild, never a
concurrent write) and emits the single source of truth:
  results/master.json          - machine-readable per-kernel list
  results/master.csv           - per-kernel, diffable/greppable
  results/master_variants.csv  - per-VARIANT spine (which SEW/LMUL/mask tested)
  results/master.md            - human-skimmable: coverage summary, surprises,
                                 per-kernel table

A "surprise" = observed status disagrees with the RTL-derived expectation
(supported->PASS, blocked_illegal->BLOCKED, blocked_silent->FAIL_INCORRECT).
These are the actionable findings.

Re-run any time new result.json files appear (and only when no sweep is
actively writing). Never edited by hand.
"""
import argparse
import csv
import glob
import json
import os

STATUS_ORDER = ["FAIL_INCORRECT", "FAIL_HANG", "BLOCKED", "ERROR_SPIKE",
                "ERROR_BUILD", "UNTESTED", "PASS"]


def is_surprise(expected, vstatus):
    if vstatus == "UNTESTED":
        return False
    if expected == "supported":
        return vstatus != "PASS"
    if expected == "blocked_illegal":
        return vstatus != "BLOCKED"
    if expected == "blocked_silent":
        return vstatus != "FAIL_INCORRECT"
    return False


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)                          # flow/verif
    ap.add_argument("--build-dir", default=os.path.join(root, "build"))
    ap.add_argument("--out-dir", default=os.path.join(root, "results"))
    ap.add_argument("--inventory", default=os.path.join(root, "inventory", "inventory.json"))
    args = ap.parse_args()

    rows = []
    for rj in sorted(glob.glob(os.path.join(args.build_dir, "*", "*", "result.json"))):
        if os.sep + "_probe" + os.sep in rj or os.sep + "_dbg" + os.sep in rj:
            continue
        try:
            rows.append(json.load(open(rj)))
        except Exception as e:
            rows.append({"name": rj, "status": "ERROR_BUILD", "note": f"unreadable: {e}"})

    os.makedirs(args.out_dir, exist_ok=True)
    json.dump(rows, open(os.path.join(args.out_dir, "master.json"), "w"), indent=2)

    # plain-English descriptions (mnemonic -> text), generated by descriptions.py
    desc_path = os.path.join(os.path.dirname(args.inventory), "descriptions.json")
    DESCR = json.load(open(desc_path)) if os.path.exists(desc_path) else {}

    # ---- Excel-friendly summary CSV (one row per instruction, plain verdicts) ----
    VERDICT = {"PASS": "WORKS", "BLOCKED": "BLOCKED-illegal", "FAIL_HANG": "HANG",
               "FAIL_INCORRECT": "INCORRECT", "ERROR_SPIKE": "ERROR(spike)",
               "ERROR_BUILD": "ERROR(build)", "UNTESTED": "UNTESTED"}

    def finding_tag(r):
        g = r.get("group", ""); mn = r.get("mnemonic", ""); st = r.get("status", ""); exp = r.get("expected", "")
        if st == "PASS":
            return ""
        if exp == "blocked_illegal" and st == "BLOCKED":
            return "as-predicted: not implemented (illegal trap)"
        if exp == "blocked_silent":
            return "as-predicted: segment silent mis-decode"
        if g.startswith("rvv-mask") or mn == "vid.v":
            return "F1 multi-cluster mask/index unit"
        if g in ("rvv-red-int", "rvv-red-fp"):
            return "F2 reductions trap @LMUL=m8"
        if g == "rvv-int-carry":
            return "F3 carry-to-mask trap @LMUL=m2"
        if g == "rvv-perm":
            return "F4 slides (SLDU) hang/wrong"
        if g == "rvv-mem-strided" or (g == "rvv-mem-indexed" and st == "FAIL_HANG"):
            return "F5 strided/scatter store hang"
        if "ff" in mn:
            return "F6 fault-only-first load hang"
        if g.startswith("rvv-fp") or g.startswith("rv64f") or g.startswith("rv64d") or mn == "scalar_basic":
            return "F7 FP special-value (signed-zero/inf-sign/fsqrt ULP)"
        if g == "rv64a":
            return "F8 atomics no-op (likely testbench memory, needs confirm)"
        if g == "rvv-mem-whole":
            return "F9 whole-register load EEW8/64 (preliminary)"
        if g == "rvv-mem-segment":
            return "as-predicted: segment silent mis-decode"
        return ""

    with open(os.path.join(args.out_dir, "summary.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Ext", "Group", "Mnemonic", "Description", "Verdict", "Partial",
                    "PASS_variants", "Total_variants", "Expected", "Surprise", "Finding", "Note"])
        for r in sorted(rows, key=lambda r: (r.get("ext", ""), r.get("group", ""), r.get("mnemonic", ""))):
            vr = r.get("variant_results", [])
            pv = sum(1 for v in vr if v["status"] == "PASS")
            tv = len(vr)
            partial = "Y" if 0 < pv < tv else ""
            ft = finding_tag(r)
            surprise = "Y" if (ft and not ft.startswith("as-predicted")) else ""
            mn = r.get("mnemonic", "")
            w.writerow([r.get("ext", ""), r.get("group", ""), mn, DESCR.get(mn, ""),
                        VERDICT.get(r.get("status", ""), r.get("status", "")), partial,
                        pv, tv, r.get("expected", ""), surprise, ft,
                        (r.get("note", "") or "").replace("\n", " ")[:120]])

    # ---- per-kernel CSV ----
    cols = ["mnemonic", "description", "ext", "group", "status", "expected", "hw_cycles",
            "exec_cycles", "wall_s", "mcause", "nr_lanes", "nr_clusters", "vlen",
            "kernel", "dump_ir", "sim_log", "note"]
    with open(os.path.join(args.out_dir, "master.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for r in rows:
            w.writerow([DESCR.get(r.get("mnemonic", ""), "") if c == "description"
                        else r.get(c, "") for c in cols])

    # ---- per-variant CSV (the detailed spine) ----
    surprises = []
    with open(os.path.join(args.out_dir, "master_variants.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["mnemonic", "ext", "group", "expected", "variant",
                    "status", "surprise", "note", "kernel"])
        for r in rows:
            exp = r.get("expected", "")
            for v in r.get("variant_results", []):
                sup = is_surprise(exp, v["status"])
                w.writerow([r.get("mnemonic", ""), r.get("ext", ""), r.get("group", ""),
                            exp, v["variant"], v["status"], "YES" if sup else "",
                            (v.get("note", "") or "")[:120], os.path.basename(r.get("kernel", ""))])
                if sup:
                    surprises.append((r.get("mnemonic", ""), r.get("group", ""), exp,
                                      v["variant"], v["status"], (v.get("note", "") or "")[:140]))

    # ---- stats ----
    by_status, by_ext_status = {}, {}
    for r in rows:
        s = r.get("status", "?"); e = r.get("ext", "?")
        by_status[s] = by_status.get(s, 0) + 1
        by_ext_status.setdefault(e, {}).setdefault(s, 0)
        by_ext_status[e][s] += 1
    inv = json.load(open(args.inventory)) if os.path.exists(args.inventory) else []
    inv_testable = [e for e in inv if e["expected"] != "absent_ext"]
    tested = {r.get("mnemonic", "") for r in rows}
    n_var = sum(len(r.get("variant_results", [])) for r in rows)

    def rank(r):
        s = r.get("status", "PASS")
        return (STATUS_ORDER.index(s) if s in STATUS_ORDER else 99,
                r.get("group", ""), r.get("mnemonic", ""))

    with open(os.path.join(args.out_dir, "master.md"), "w") as f:
        f.write("# AZilla RVV 1.0 + RV64 verification - master tracking log\n\n")
        f.write("Generated by `flow/verif/scripts/merge.py`. Oracle = Spike reference model "
                "(differential, vlen:4096); DUT = AraXL Verilator RTL (NR_LANES=4, NR_CLUSTERS=4, "
                "architectural VLEN=16384). PASS = bit-exact vs Spike on all active elements.\n\n")
        f.write("## Coverage summary\n\n")
        f.write(f"- kernels with results: **{len(rows)}**  (variants verdicted: **{n_var}**)\n")
        for s in STATUS_ORDER:
            if by_status.get(s):
                f.write(f"  - kernel `{s}`: {by_status[s]}\n")
        f.write(f"- inventory testable mnemonics (excl. absent-ext): {len(inv_testable)}; "
                f"distinct mnemonics with a result: {len(tested & {e['mnemonic'] for e in inv_testable})}\n\n")
        f.write("### By extension (kernel-level)\n\n| Ext | " + " | ".join(STATUS_ORDER) + " |\n")
        f.write("|---|" + "---|" * len(STATUS_ORDER) + "\n")
        for e in sorted(by_ext_status):
            f.write(f"| {e} | " + " | ".join(str(by_ext_status[e].get(s, 0)) for s in STATUS_ORDER) + " |\n")

        f.write(f"\n## Surprises / findings ({len(surprises)})\n\n")
        f.write("Observed status disagrees with the RTL-derived expectation. These are the "
                "actionable items.\n\n")
        if surprises:
            f.write("| Mnemonic | Group | Expected | Variant | Observed | Note |\n|---|---|---|---|---|---|\n")
            for mn, g, exp, var, st, note in surprises:
                f.write(f"| `{mn}` | {g} | {exp} | {var} | **{st}** | {note.replace('|','/')} |\n")
        else:
            f.write("_None so far._\n")

        f.write("\n## Per-kernel results (most-severe first)\n\n")
        f.write("| Mnemonic | Ext | Group | Status | Expected | Variants(P/total) | hw_cyc | wall_s | Note |\n")
        f.write("|---|---|---|---|---|---|---|---|---|\n")
        for r in sorted(rows, key=rank):
            vc = r.get("variant_counts", {})
            vr = r.get("variant_results", [])
            note = (r.get("note", "") or "").replace("|", "/")[:80]
            f.write("| `{m}` | {x} | {g} | **{s}** | {e} | {p}/{t} | {hc} | {w} | {n} |\n".format(
                m=r.get("mnemonic", "?"), x=r.get("ext", ""), g=r.get("group", ""),
                s=r.get("status", "?"), e=r.get("expected", ""),
                p=vc.get("PASS", 0), t=len(vr),
                hc=r.get("hw_cycles", ""), w=r.get("wall_s", ""), n=note))

    print(f"merged {len(rows)} kernels / {n_var} variants -> {args.out_dir}/master.*")
    print(f"  surprises (observed != expected): {len(surprises)}")
    for s in STATUS_ORDER:
        if by_status.get(s):
            print(f"  kernel {s}: {by_status[s]}")


if __name__ == "__main__":
    main()
