/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vmv.v.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * vmv.v.v/.v.x/.v.i splat/copy
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e8,m1,ta,ma\n"
    "vle8.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse8.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e8("vmv.v.v e8 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e16,m1,ta,ma\n"
    "vle16.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse16.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e16("vmv.v.v e16 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.v.v e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e64,m1,ta,ma\n"
    "vle64.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse64.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e64("vmv.v.v e64 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "li t1,21\n"
    "vmv.v.x v24,t1\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.v.x e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vmv.v.i v24,5\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.v.i e32 m1 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m2,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.v.v e32 m2 avl=37", R, 37);

    asm volatile(
    "vsetvli t0,%[vl],e32,m8,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vmv.v.v v24,v8\n"
    "vse32.v v24,(%[R])\n"
    :: [A]"r"(A),[B]"r"(B),[R]"r"(R),[M]"r"(M),[vl]"r"(37UL) : "t0","t1","memory");
    report_e32("vmv.v.v e32 m8 avl=37", R, 37);
    VEND();
    return 0;
}
