/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed test for vsseg2e32.v.
 * Differential vs Spike; per-variant #V blocks. Do not hand-edit; regenerate.
 * unit-stride segment store: silent mis-decode
 */
#include "verif.h"

static uint8_t A[2048] L2BUF;
static uint8_t B[2048] L2BUF;
static uint8_t R[4096] L2BUF;
static uint8_t D0[2048] L2BUF;
static uint8_t M[256]  L2BUF;
static uint8_t IDX[512] L2BUF;   /* index vector for indexed load/store (filled per-kernel) */

static void fill(void) {
    for (int i = 0; i < 2048; i++) {
        A[i]  = (uint8_t)(i * 7u + 3u);
        B[i]  = (uint8_t)((i * 13u + 131u) | 1u);   /* nonzero (safe for divide) */
        D0[i] = (uint8_t)(0xC0u + i);
    }
    for (int i = 0; i < 256; i++) M[i] = (uint8_t)(0xA5u ^ (i * 3u));
}

int main(void) {
    fill();
    VBEGIN();
    asm volatile(
    "vsetvli t0,%[vl],e32,m1,ta,ma\n"
    "vle32.v v8,(%[A])\n"
    "vsseg2e32.v v8,(%[R])\n"
    :: [A]"r"(A),[R]"r"(R),[I]"r"(IDX),[st]"r"(8UL),[vl]"r"(16UL) : "t0","t1","memory");
    report_e32("vsseg2e32.v m1 avl=16", R, 16);
    VEND();
    return 0;
}
