/* AUTO-GENERATED by flow/verif/scripts/gen_kernels.py - directed RV64 scalar test
 * for sw. Runs the instruction on fixed operand sets; differential vs Spike.
 * FP ops pin frm=RNE. Do not hand-edit; regenerate.
 * 
 */
#include "verif.h"

static uint64_t R[256] L2BUF;     /* scalar results */
static uint64_t MEM[64] L2BUF;    /* memory for loads/stores/atomics */

static void fill(void) {
    for (int i = 0; i < 64; i++) MEM[i] = 0x1100u * i + 0x0123456789ABCDEFULL;
}

int main(void) {
    fill();
    VBEGIN();
    long o;
    for (int i=0;i<64;i++) ((volatile uint64_t*)MEM)[i]=0;
    asm volatile("sw %0,0(%1)"::"r"(0x1122334455667788L),"r"(MEM):"memory");
    asm volatile("ld %0,0(%1)":"=r"(o):"r"(MEM)); R[0]=(uint64_t)o & 0xFFFFFFFFULL;
    asm volatile("sw %0,8(%1)"::"r"(0xFFFFFFFFFFFFFFFFL),"r"(MEM):"memory");
    asm volatile("ld %0,8(%1)":"=r"(o):"r"(MEM)); R[1]=(uint64_t)o & 0xFFFFFFFFULL;
    asm volatile("sw %0,16(%1)"::"r"(0x00000000DEADBEEFL),"r"(MEM):"memory");
    asm volatile("ld %0,16(%1)":"=r"(o):"r"(MEM)); R[2]=(uint64_t)o & 0xFFFFFFFFULL;
    report_e64("sw", R, 3);
    VEND();
    return 0;
}
